Indent using four spaces instead of two

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -7,14 +7,14 @@ DOTFILES_GIT_REMOTE="https://github.com/kevva/dotfiles"
 
 # If missing, download and extract the dotfiles repository
 if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
-  printf "$(tput setaf 7)Downloading dotfiles...$(tput sgr0)\n"
-  mkdir ${DOTFILES_DIRECTORY}
-  # Get the tarball
-  curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOTFILES_GIT_REMOTE}/tarball/master
-  # Extract to the dotfiles directory
-  tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
-  # Remove the tarball
-  rm -rf ${HOME}/dotfiles.tar.gz
+    printf "$(tput setaf 7)Downloading dotfiles...$(tput sgr0)\n"
+    mkdir ${DOTFILES_DIRECTORY}
+    # Get the tarball
+    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOTFILES_GIT_REMOTE}/tarball/master
+    # Extract to the dotfiles directory
+    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
+    # Remove the tarball
+    rm -rf ${HOME}/dotfiles.tar.gz
 fi
 
 # Source lib files
@@ -28,136 +28,136 @@ source ./lib/subl
 
 # Help text
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-  run_help
-  exit
+    run_help
+    exit
 fi
 
 # Help text
 if [[ "$1" == "-l" || "$1" == "--list" ]]; then
-  run_list
-  exit
+    run_list
+    exit
 fi
 
 # Test for known flags
 for opt in $@
 do
-  case $opt in
-    -np|--no-packages) no_packages=true ;;
-    -ns|--no-sync) no_sync=true ;;
-    -*|--*) log_warning "Warning: invalid option $opt" ;;
-  esac
+    case $opt in
+        -np|--no-packages) no_packages=true ;;
+        -ns|--no-sync) no_sync=true ;;
+        -*|--*) log_warning "Warning: invalid option $opt" ;;
+    esac
 done
 
 # Before relying on Homebrew, check that packages can be compiled
 if ! type_exists 'gcc'; then
-  log_error "The XCode Command Line Tools must be installed first."
-  printf "  Download them from: https://developer.apple.com/downloads\n"
-  printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
-  exit 1
+    log_error "The XCode Command Line Tools must be installed first."
+    printf "  Download them from: https://developer.apple.com/downloads\n"
+    printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
+    exit 1
 fi
 
 # Check for Homebrew
 if ! type_exists 'brew'; then
-  log_header "Installing Homebrew..."
-  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
+    log_header "Installing Homebrew..."
+    ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
 fi
 
 # Check for git
 if ! type_exists 'git'; then
-  log_header "Updating Homebrew..."
-  brew update
-  log_header "Installing Git..."
-  brew install git
+    log_header "Updating Homebrew..."
+    brew update
+    log_header "Installing Git..."
+    brew install git
 fi
 
 # Initialize the git repository if it's missing
 if ! is_git_repo; then
-  log_header "Initializing git repository..."
-  git init
-  git remote add origin ${DOTFILES_GIT_REMOTE}
-  git fetch origin master
-  # Reset the index and working tree to the fetched HEAD
-  # (submodules are cloned in the subsequent sync step)
-  git reset --hard FETCH_HEAD
-  # Remove any untracked files
-  git clean -fd
+    log_header "Initializing git repository..."
+    git init
+    git remote add origin ${DOTFILES_GIT_REMOTE}
+    git fetch origin master
+    # Reset the index and working tree to the fetched HEAD
+    # (submodules are cloned in the subsequent sync step)
+    git reset --hard FETCH_HEAD
+    # Remove any untracked files
+    git clean -fd
 fi
 
 # Conditionally sync with the remote repository
 if [[ $no_sync ]]; then
-  printf "Skipped dotfiles sync.\n"
+    printf "Skipped dotfiles sync.\n"
 else
-  log_header "Syncing dotfiles..."
-  # Pull down the latest changes
-  git pull --rebase origin master
-  # Update submodules
-  git submodule update --recursive --init --quiet
+    log_header "Syncing dotfiles..."
+    # Pull down the latest changes
+    git pull --rebase origin master
+    # Update submodules
+    git submodule update --recursive --init --quiet
 fi
 
 # Install and update packages
 if [[ $no_packages ]]; then
-  printf "Skipped package installations.\n"
+    printf "Skipped package installations.\n"
 else
-  printf "Updating packages...\n"
-  # Install Homebrew formulae
-  run_brew
-  # Install Node packages
-  run_npm
+    printf "Updating packages...\n"
+    # Install Homebrew formulae
+    run_brew
+    # Install Node packages
+    run_npm
 fi
 
 link() {
-  # Force create/replace the symlink.
-  ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
+    # Force create/replace the symlink.
+    ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
 }
 
 mirrorfiles() {
-  # Copy `.gitconfig`.
-  # Any global git commands in `~/.bash_profile.local` will be written to
-  # `.gitconfig`. This prevents them being committed to the repository.
-  rsync -avz --quiet ${DOTFILES_DIRECTORY}/git/gitconfig  ${HOME}/.gitconfig
+    # Copy `.gitconfig`.
+    # Any global git commands in `~/.bash_profile.local` will be written to
+    # `.gitconfig`. This prevents them being committed to the repository.
+    rsync -avz --quiet ${DOTFILES_DIRECTORY}/git/gitconfig  ${HOME}/.gitconfig
 
-  # Create the necessary symbolic links between the `.dotfiles` and `HOME`
-  # directory. The `bash_profile` sources other files directly from the
-  # `.dotfiles` repository.
-  link "bash/bashrc"        ".bashrc"
-  link "bash/bash_profile"  ".bash_profile"
-  link "bash/inputrc"       ".inputrc"
-  link "git/gitattributes"  ".gitattributes"
-  link "git/gitignore"      ".gitignore"
+    # Create the necessary symbolic links between the `.dotfiles` and `HOME`
+    # directory. The `bash_profile` sources other files directly from the
+    # `.dotfiles` repository.
+    link "bash/bashrc"        ".bashrc"
+    link "bash/bash_profile"  ".bash_profile"
+    link "bash/inputrc"       ".inputrc"
+    link "git/gitattributes"  ".gitattributes"
+    link "git/gitignore"      ".gitignore"
 
-  log_success "Dotfiles update complete!"
+    log_success "Dotfiles update complete!"
 }
 
 if [[ ! $no_sync ]]; then
-  # Ask before potentially overwriting files
-  seek_confirmation "Warning: This step may overwrite your existing dotfiles."
+    # Ask before potentially overwriting files
+    seek_confirmation "Warning: This step may overwrite your existing dotfiles."
 
-  if is_confirmed; then
-    mirrorfiles
-    source ${HOME}/.bash_profile
-  else
-    printf "Aborting...\n"
-    exit 1
-  fi
+    if is_confirmed; then
+        mirrorfiles
+        source ${HOME}/.bash_profile
+    else
+        printf "Aborting...\n"
+        exit 1
+    fi
 fi
 
 if [[ ! $no_sync ]]; then
-  # Ask before potentially overwriting Sublime Text 2 preferences
-  seek_confirmation "Warning: This step may overwrite your existing Sublime Text 2 preferences."
+    # Ask before potentially overwriting Sublime Text 2 preferences
+    seek_confirmation "Warning: This step may overwrite your existing Sublime Text 2 preferences."
 
-  if is_confirmed; then
-    run_subl
-  else
-    printf "Skipped installing Sublime Text 2 preferences.\n"
-  fi
+    if is_confirmed; then
+        run_subl
+    else
+        printf "Skipped installing Sublime Text 2 preferences.\n"
+    fi
 fi
 
 # Ask before potentially overwriting OS X defaults
 seek_confirmation "Warning: This step may modify your OS X system defaults."
 
 if is_confirmed; then
-  bash ./bin/osxdefaults
-  log_success "OS X settings updated! You may need to restart."
+    bash ./bin/osxdefaults
+    log_success "OS X settings updated! You may need to restart."
 else
-  printf "Skipped OS X settings update.\n"
+    printf "Skipped OS X settings update.\n"
 fi
diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -2,59 +2,59 @@
 # Homebrew formulae installation
 
 run_brew() {
-  # Check for Homebrew
-  if type_exists 'brew'; then
-    log_header "Updating Homebrew..."
-    # Use the latest version of Homebrew
-    brew update
-    [[ $? ]] && log_success "Done"
+    # Check for Homebrew
+    if type_exists 'brew'; then
+        log_header "Updating Homebrew..."
+        # Use the latest version of Homebrew
+        brew update
+        [[ $? ]] && log_success "Done"
 
-    log_header "Updating any existing Homebrew formulae..."
-    # Upgrade any already-installed formulae
-    brew upgrade
-    [[ $? ]] && log_success "Done"
+        log_header "Updating any existing Homebrew formulae..."
+        # Upgrade any already-installed formulae
+        brew upgrade
+        [[ $? ]] && log_success "Done"
 
-    log_header "Checking status of desired Homebrew formulae..."
-    local list_formulae
-    local -a missing_formulae
-    local -a desired_formulae=(
-      'coreutils' # GNU core utilities (those that come with OS X are outdated)
-      'git'
-      'ack'
-      'bash-completion'
-      'jpeg'
-      'node'
-      'optipng'
-      'phantomjs'
-      'tree'
-      'wget'
-    )
+        log_header "Checking status of desired Homebrew formulae..."
+        local list_formulae
+        local -a missing_formulae
+        local -a desired_formulae=(
+            'coreutils' # GNU core utilities (those that come with OS X are outdated)
+            'git'
+            'ack'
+            'bash-completion'
+            'jpeg'
+            'node'
+            'optipng'
+            'phantomjs'
+            'tree'
+            'wget'
+        )
 
-    for index in ${!desired_formulae[*]}
-    do
-      if ! formula_exists ${desired_formulae[$index]}; then
-        # Store the name (and options) of every missing formula
-        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
-      fi
-    done
+        for index in ${!desired_formulae[*]}
+        do
+            if ! formula_exists ${desired_formulae[$index]}; then
+                # Store the name (and options) of every missing formula
+                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
+            fi
+        done
 
-    if [[ "$missing_formulae" ]]; then
-      # Convert the array of missing formula into a list of space-separate strings
-      list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+        if [[ "$missing_formulae" ]]; then
+            # Convert the array of missing formula into a list of space-separate strings
+            list_formulae=$( printf "%s " "${missing_formulae[@]}" )
 
-      log_header "Installing missing Homebrew formulae..."
-      # Install all missing formulae
-      brew install $list_formulae
+            log_header "Installing missing Homebrew formulae..."
+            # Install all missing formulae
+            brew install $list_formulae
 
-      [[ $? ]] && log_success "Done"
+            [[ $? ]] && log_success "Done"
+        fi
+
+        # Remove outdated versions from the Cellar
+        brew cleanup
+    else
+        printf "\n"
+        log_error "Error: Homebrew not found."
+        printf "Aborting...\n"
+        exit
     fi
-
-    # Remove outdated versions from the Cellar
-    brew cleanup
-  else
-    printf "\n"
-    log_error "Error: Homebrew not found."
-    printf "Aborting...\n"
-    exit
-  fi
 }
diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -2,21 +2,21 @@
 # npm package installation
 
 run_npm() {
-  # Check for npm
-  if type_exists 'npm'; then
-    log_header "Installing Node.js packages..."
+    # Check for npm
+    if type_exists 'npm'; then
+        log_header "Installing Node.js packages..."
 
-    # List of npm packages
-    local packages="bower grunt-cli jshint"
+        # List of npm packages
+        local packages="bower grunt-cli jshint"
 
-    # Install packages globally and quietly
-    npm install $packages --global --quiet
+        # Install packages globally and quietly
+        npm install $packages --global --quiet
 
-    [[ $? ]] && log_success "Done"
-  else
-    printf "\n"
-    log_error "Error: npm not found."
-    printf "Aborting...\n"
-    exit
-  fi
+        [[ $? ]] && log_success "Done"
+    else
+        printf "\n"
+        log_error "Error: npm not found."
+        printf "Aborting...\n"
+        exit
+    fi
 }
