Use tabs instead of spaces

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -8,248 +8,248 @@ readonly DOTFILES_TARBALL_PATH="https://github.com/kevva/dotfiles/tarball/master
 
 # Parse options
 parse_opts() {
-    for opt in $@
-    do
-        case ${opt} in
-            --help) help=true ;;
-            --no-packages) no_packages=true ;;
-            --no-sync) no_sync=true ;;
-            -*|--*) log_warning "Warning: invalid option ${opt}" ;;
-        esac
-    done
+	for opt in $@
+	do
+		case ${opt} in
+			--help) help=true ;;
+			--no-packages) no_packages=true ;;
+			--no-sync) no_sync=true ;;
+			-*|--*) log_warning "Warning: invalid option ${opt}" ;;
+		esac
+	done
 }
 
 # If missing, download and extract the dotfiles repository
 check_dotfiles() {
-    if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
-        printf "$(tput setaf 7)Downloading dotfiles...$(tput sgr0)\n"
-        mkdir ${DOTFILES_DIRECTORY}
-        curl -fsSL ${DOTFILES_TARBALL_PATH} | tar -xzC ${DOTFILES_DIRECTORY} --strip-components 1
-    fi
+	if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
+		printf "$(tput setaf 7)Downloading dotfiles...$(tput sgr0)\n"
+		mkdir ${DOTFILES_DIRECTORY}
+		curl -fsSL ${DOTFILES_TARBALL_PATH} | tar -xzC ${DOTFILES_DIRECTORY} --strip-components 1
+	fi
 }
 
 # Before relying on Homebrew, check that packages can be compiled
 check_gcc() {
-    if ! type_exists 'gcc' && is_os 'darwin'; then
-        log_error "The XCode Command Line Tools must be installed first"
-        printf "  Download them from: https://developer.apple.com/downloads\n"
-        printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
-        exit 1
-    fi
+	if ! type_exists 'gcc' && is_os 'darwin'; then
+		log_error "The XCode Command Line Tools must be installed first"
+		printf "  Download them from: https://developer.apple.com/downloads\n"
+		printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
+		exit 1
+	fi
 }
 
 # Check for Homebrew
 check_brew() {
-    if ! type_exists 'brew' && is_os 'darwin'; then
-        log_header "Installing Homebrew..."
-        ruby -e "$(curl -fsSkL https://raw.github.com/Homebrew/homebrew/go/install)"
-    fi
+	if ! type_exists 'brew' && is_os 'darwin'; then
+		log_header "Installing Homebrew..."
+		ruby -e "$(curl -fsSkL https://raw.github.com/Homebrew/homebrew/go/install)"
+	fi
 }
 
 # Check for git
 check_git() {
-    if ! type_exists 'git'; then
-        if is_os 'darwin'; then
-            log_header "Installing Git..."
-            brew update &> /dev/null
-            brew install git
-        elif is_os 'linux'; then
-            log_header "Installing Git..."
-            sudo apt-get update -qqy &> /dev/null
-            sudo apt-get install --allow-unauthenticated -qqy git-core
-        fi
-    fi
+	if ! type_exists 'git'; then
+		if is_os 'darwin'; then
+			log_header "Installing Git..."
+			brew update &> /dev/null
+			brew install git
+		elif is_os 'linux'; then
+			log_header "Installing Git..."
+			sudo apt-get update -qqy &> /dev/null
+			sudo apt-get install --allow-unauthenticated -qqy git-core
+		fi
+	fi
 }
 
 # Check for nvm
 check_nvm() {
-    if ! type_exists 'node'; then
-        log_header "Installing nvm..."
-        curl -fsSL https://raw.githubusercontent.com/creationix/nvm/v0.14.0/install.sh | bash
-        source ${HOME}/.nvm/nvm.sh
-    fi
+	if ! type_exists 'node'; then
+		log_header "Installing nvm..."
+		curl -fsSL https://raw.githubusercontent.com/creationix/nvm/v0.14.0/install.sh | bash
+		source ${HOME}/.nvm/nvm.sh
+	fi
 }
 
 # Check for node
 check_node() {
-    local version="0.10"
+	local version="0.10"
 
-    if ! type_exists 'node'; then
-        log_header "Installing node..."
-        nvm install ${version}
-        nvm alias default ${version}
-    fi
+	if ! type_exists 'node'; then
+		log_header "Installing node..."
+		nvm install ${version}
+		nvm alias default ${version}
+	fi
 }
 
 # Initialize the git repository if it's missing
 run_init() {
-    if ! is_git_repo; then
-        log_header "Initializing git repository..."
-        git init &> /dev/null
-        git remote add origin ${DOTFILES_GIT_REMOTE} &> /dev/null
-    fi
+	if ! is_git_repo; then
+		log_header "Initializing git repository..."
+		git init &> /dev/null
+		git remote add origin ${DOTFILES_GIT_REMOTE} &> /dev/null
+	fi
 }
 
 # Conditionally sync with the remote repository
 run_sync() {
-    if [[ ${no_sync} ]]; then
-        printf "Skipped dotfiles sync\n"
-    else
-        log_header "Syncing dotfiles..."
-        git fetch origin master
-        # Reset the index and working tree to the fetched HEAD
-        # (submodules are cloned in the subsequent sync step)
-        git reset --hard FETCH_HEAD
-        # Remove any untracked files
-        git clean -fd
-    fi
+	if [[ ${no_sync} ]]; then
+		printf "Skipped dotfiles sync\n"
+	else
+		log_header "Syncing dotfiles..."
+		git fetch origin master
+		# Reset the index and working tree to the fetched HEAD
+		# (submodules are cloned in the subsequent sync step)
+		git reset --hard FETCH_HEAD
+		# Remove any untracked files
+		git clean -fd
+	fi
 }
 
 # Install and update packages
 run_packages() {
-    if [[ ${no_packages} ]]; then
-        printf "Skipped package installations\n"
-    else
-        if is_os 'linux'; then
-            source ./lib/apt
-            run_apt
-        elif is_os 'darwin'; then
-            source ./lib/brew
-            run_brew
-        fi
+	if [[ ${no_packages} ]]; then
+		printf "Skipped package installations\n"
+	else
+		if is_os 'linux'; then
+			source ./lib/apt
+			run_apt
+		elif is_os 'darwin'; then
+			source ./lib/brew
+			run_brew
+		fi
 
-        source ./lib/npm
-        run_npm
-    fi
+		source ./lib/npm
+		run_npm
+	fi
 }
 
 # Fix privacy related issues present in Ubuntu
 privacy() {
-    if is_os 'linux'; then
-        wget -qO - https://fixubuntu.com/fixubuntu.sh | bash &> /dev/null
-    fi
+	if is_os 'linux'; then
+		wget -qO - https://fixubuntu.com/fixubuntu.sh | bash &> /dev/null
+	fi
 }
 
 # Force create/replace symlink
 link() {
-    ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
+	ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
 }
 
 # Copy and symlink files
 mirrorfiles() {
-    # Copy `.gitconfig`.
-    # Any global git commands in `~/.bash_profile.local` will be written to
-    # `.gitconfig`. This prevents them being committed to the repository.
-    rsync -avz --quiet ${DOTFILES_DIRECTORY}/git/gitconfig  ${HOME}/.gitconfig
+	# Copy `.gitconfig`.
+	# Any global git commands in `~/.bash_profile.local` will be written to
+	# `.gitconfig`. This prevents them being committed to the repository.
+	rsync -avz --quiet ${DOTFILES_DIRECTORY}/git/gitconfig  ${HOME}/.gitconfig
 
-    # Create the necessary symbolic links between the `.dotfiles` and `HOME`
-    # directory. The `bash_profile` sources other files directly from the
-    # `.dotfiles` repository.
-    link "bash/bashrc"        ".bashrc"
-    link "bash/bash_profile"  ".bash_profile"
-    link "bash/inputrc"       ".inputrc"
-    link "git/gitattributes"  ".gitattributes"
-    link "git/gitignore"      ".gitignore"
+	# Create the necessary symbolic links between the `.dotfiles` and `HOME`
+	# directory. The `bash_profile` sources other files directly from the
+	# `.dotfiles` repository.
+	link "bash/bashrc"		".bashrc"
+	link "bash/bash_profile"  ".bash_profile"
+	link "bash/inputrc"	   ".inputrc"
+	link "git/gitattributes"  ".gitattributes"
+	link "git/gitignore"	  ".gitignore"
 }
 
 # Ask before potentially overwriting files
 confirm_dotfiles() {
-    seek_confirmation "Warning: This step may overwrite your existing dotfiles"
+	seek_confirmation "Warning: This step may overwrite your existing dotfiles"
 
-    if is_confirmed; then
-        mirrorfiles
-        log_success "Dotfiles update complete!"
-        source ${HOME}/.bash_profile
-    else
-        printf "Aborting...\n"
-        exit 1
-    fi
+	if is_confirmed; then
+		mirrorfiles
+		log_success "Dotfiles update complete!"
+		source ${HOME}/.bash_profile
+	else
+		printf "Aborting...\n"
+		exit 1
+	fi
 }
 
 # Ask before potentially overwriting OS X defaults
 confirm_osx() {
-    if is_os 'darwin'; then
-        seek_confirmation "Warning: This step may modify your OS X system defaults"
+	if is_os 'darwin'; then
+		seek_confirmation "Warning: This step may modify your OS X system defaults"
 
-        if is_confirmed; then
-            bash ./bin/osxdefaults
-            log_success "OS X settings updated!"
-        else
-            printf "Skipped OS X settings update\n"
-        fi
-    fi
+		if is_confirmed; then
+			bash ./bin/osxdefaults
+			log_success "OS X settings updated!"
+		else
+			printf "Skipped OS X settings update\n"
+		fi
+	fi
 }
 
 # Ask before potentially overwriting Ubuntu defaults
 confirm_ubuntu() {
-    if is_os 'linux'; then
-        seek_confirmation "Warning: This step may modify your Ubuntu system defaults"
+	if is_os 'linux'; then
+		seek_confirmation "Warning: This step may modify your Ubuntu system defaults"
 
-        if is_confirmed; then
-            bash ./bin/ubuntudefaults
-            log_success "Ubuntu settings updated!"
-        else
-            printf "Skipped Ubuntu settings update\n"
-        fi
-    fi
+		if is_confirmed; then
+			bash ./bin/ubuntudefaults
+			log_success "Ubuntu settings updated!"
+		else
+			printf "Skipped Ubuntu settings update\n"
+		fi
+	fi
 }
 
 # Ask before potentially overwriting ST3 preferences
 confirm_slt() {
-    seek_confirmation "Warning: This step may overwrite your existing ST3 preferences"
+	seek_confirmation "Warning: This step may overwrite your existing ST3 preferences"
 
-    if is_confirmed; then
-        source ./lib/subl
-        run_subl
-        log_success "ST3 preferences updated!"
-    else
-        printf "Skipped ST3 preferences update\n"
-    fi
+	if is_confirmed; then
+		source ./lib/subl
+		run_subl
+		log_success "ST3 preferences updated!"
+	else
+		printf "Skipped ST3 preferences update\n"
+	fi
 }
 
 # Run
 run() {
-    # Check if dotfiles are installed
-    check_dotfiles
+	# Check if dotfiles are installed
+	check_dotfiles
 
-    # cd into ~/.dotfiles
-    cd ${DOTFILES_DIRECTORY}
+	# cd into ~/.dotfiles
+	cd ${DOTFILES_DIRECTORY}
 
-    # Source utils
-    source ./lib/utils
+	# Source utils
+	source ./lib/utils
 
-    # Parse options
-    parse_opts "$@"
+	# Parse options
+	parse_opts "$@"
 
-    # Show help
-    if [[ ${help} ]]; then
-        source ./lib/help
-        run_help
-        exit
-    fi
+	# Show help
+	if [[ ${help} ]]; then
+		source ./lib/help
+		run_help
+		exit
+	fi
 
-    # Run checks
-    check_gcc
-    check_brew
-    check_git
-    check_nvm
-    check_node
+	# Run checks
+	check_gcc
+	check_brew
+	check_git
+	check_nvm
+	check_node
 
-    # Init repo and sync files
-    run_init
-    run_sync
+	# Init repo and sync files
+	run_init
+	run_sync
 
-    # Install packages
-    run_packages
+	# Install packages
+	run_packages
 
-    # Fix privacy settings in Ubuntu
-    privacy
+	# Fix privacy settings in Ubuntu
+	privacy
 
-    # Confirm before applying settings
-    confirm_dotfiles
-    confirm_osx
-    confirm_ubuntu
-    confirm_slt
+	# Confirm before applying settings
+	confirm_dotfiles
+	confirm_osx
+	confirm_ubuntu
+	confirm_slt
 }
 
 run "$@"
diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -2,57 +2,57 @@
 # brew
 
 run_brew() {
-    # Check for Homebrew
-    if type_exists 'brew'; then
-        log_header "Updating any existing Homebrew formulae..."
+	# Check for Homebrew
+	if type_exists 'brew'; then
+		log_header "Updating any existing Homebrew formulae..."
 
-        # Use the latest version of Homebrew
-        brew update &> /dev/null
+		# Use the latest version of Homebrew
+		brew update &> /dev/null
 
-        # Upgrade any already-installed formulae
-        brew upgrade
-        [[ $? ]] && log_success "Done"
+		# Upgrade any already-installed formulae
+		brew upgrade
+		[[ $? ]] && log_success "Done"
 
-        local list_formulae
-        local -a missing_formulae
-        local -a desired_formulae=(
-            'coreutils'
-            'git'
-            'ack'
-            'bash'
-            'bash-completion'
-            'tree'
-            'wget'
-        )
+		local list_formulae
+		local -a missing_formulae
+		local -a desired_formulae=(
+			'coreutils'
+			'git'
+			'ack'
+			'bash'
+			'bash-completion'
+			'tree'
+			'wget'
+		)
 
-        # Store the name (and options) of every missing formula
-        for i in ${!desired_formulae[*]}
-        do
-            if ! formula_exists ${desired_formulae[$i]}; then
-                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$i]}")
-            fi
-        done
+		# Store the name (and options) of every missing formula
+		for i in ${!desired_formulae[*]}
+		do
+			if ! formula_exists ${desired_formulae[$i]}; then
+				missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$i]}")
+			fi
+		done
 
-        if [[ "${missing_formulae}" ]]; then
-            # Convert the array of missing formula into a list of space-separate strings
-            list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+		if [[ "${missing_formulae}" ]]; then
+			# Convert the array of missing formula into a list of space-separate strings
+			list_formulae=$( printf "%s " "${missing_formulae[@]}" )
 
-            log_header "Installing missing Homebrew formulae..."
+			log_header "Installing missing Homebrew formulae..."
 
-            # Install all missing formulae
-            brew install ${list_formulae}
-            [[ $? ]] && log_success "Done"
-        fi
+			# Install all missing formulae
+			brew install ${list_formulae}
+			[[ $? ]] && log_success "Done"
+		fi
 
-        # Install latest rsync
-        brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb
+		# Install latest rsync
+		brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb
 
-        # Remove outdated versions from the Cellar
-        brew cleanup
-    else
-        printf "\n"
-        log_error "Error: Homebrew not found"
-        printf "Aborting...\n"
-        exit
-    fi
+		# Remove outdated versions from the Cellar
+		brew cleanup
+	else
+		printf "\n"
+		log_error "Error: Homebrew not found"
+		printf "Aborting...\n"
+		exit
+	fi
 }
diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -2,54 +2,54 @@
 # npm
 
 run_npm() {
-    # Check for npm
-    if type_exists 'npm'; then
-        # Setup global packages directory
-        mkdir -p "${HOME}/.npm-packages"
+	# Check for npm
+	if type_exists 'npm'; then
+		# Setup global packages directory
+		mkdir -p "${HOME}/.npm-packages"
 
-        # Config npm
-        npm config set prefix "${HOME}/.npm-packages"
-        npm config set email "kevinmartensson@gmail.com"
+		# Config npm
+		npm config set prefix "${HOME}/.npm-packages"
+		npm config set email "kevinmartensson@gmail.com"
 
-        log_header "Updating any existing npm packages..."
+		log_header "Updating any existing npm packages..."
 
-        # Update any already-installed packages
-        npm update --global --quiet
-        [[ $? ]] && log_success "Done"
+		# Update any already-installed packages
+		npm update --global --quiet
+		[[ $? ]] && log_success "Done"
 
-        local list_packages
-        local -a missing_packages
-        local -a desired_packages=(
-            'duo'
-            'gulp'
-            'imagemin'
-            'jscs'
-            'jshint'
-            'trash'
-        )
+		local list_packages
+		local -a missing_packages
+		local -a desired_packages=(
+			'duo'
+			'gulp'
+			'imagemin'
+			'jscs'
+			'jshint'
+			'trash'
+		)
 
-        # Store the name (and options) of every missing package
-        for i in ${!desired_packages[*]}
-        do
-            if ! type_exists ${desired_packages[$i]}; then
-                missing_packages=("${missing_packages[@]}" "${desired_packages[$i]}")
-            fi
-        done
+		# Store the name (and options) of every missing package
+		for i in ${!desired_packages[*]}
+		do
+			if ! type_exists ${desired_packages[$i]}; then
+				missing_packages=("${missing_packages[@]}" "${desired_packages[$i]}")
+			fi
+		done
 
-        if [[ "${missing_packages}" ]]; then
-            # Convert the array of missing packages into a list of space-separate strings
-            list_packages=$( printf "%s " "${missing_packages[@]}" )
+		if [[ "${missing_packages}" ]]; then
+			# Convert the array of missing packages into a list of space-separate strings
+			list_packages=$( printf "%s " "${missing_packages[@]}" )
 
-            log_header "Installing missing npm packages..."
+			log_header "Installing missing npm packages..."
 
-            # Install all missing packages
-            npm install --global --quiet ${list_packages}
-            [[ $? ]] && log_success "Done"
-        fi
-    else
-        printf "\n"
-        log_error "Error: npm not found"
-        printf "Aborting...\n"
-        exit 1
-    fi
+			# Install all missing packages
+			npm install --global --quiet ${list_packages}
+			[[ $? ]] && log_success "Done"
+		fi
+	else
+		printf "\n"
+		log_error "Error: npm not found"
+		printf "Aborting...\n"
+		exit 1
+	fi
 }
