bin: Make use of functions for everything

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,105 +1,122 @@
 #!/bin/bash
-# dotfiles installation script
+# dotfiles
+set -e
 
-DOTFILES_DIRECTORY="${HOME}/.dotfiles"
-DOTFILES_GIT_REMOTE="git@github.com:kevva/dotfiles.git"
-DOTFILES_TARBALL_PATH="https://github.com/kevva/dotfiles/tarball/master"
+readonly DOTFILES_DIRECTORY="${HOME}/.dotfiles"
+readonly DOTFILES_GIT_REMOTE="https://github.com/kevva/dotfiles.git"
+readonly DOTFILES_TARBALL_PATH="https://github.com/kevva/dotfiles/tarball/master"
+
+# Parse options
+parse_opts() {
+    for opt in $@
+    do
+        case ${opt} in
+            --help) help=true ;;
+            --no-packages) no_packages=true ;;
+            --no-sync) no_sync=true ;;
+            -*|--*) log_warning "Warning: invalid option ${opt}" ;;
+        esac
+    done
+}
 
 # If missing, download and extract the dotfiles repository
-if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
-    printf "$(tput setaf 7)Downloading dotfiles...$(tput sgr0)\n"
-    mkdir ${DOTFILES_DIRECTORY}
-    curl -fsSL ${DOTFILES_TARBALL_PATH} | tar -xzC ${DOTFILES_DIRECTORY} --strip-components 1
-fi
-
-cd ${DOTFILES_DIRECTORY}
-
-# Source lib files
-source ./lib/help
-source ./lib/utils
-source ./lib/brew
-source ./lib/npm
-source ./lib/subl
-
-# Help screen
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-    run_help
-    exit
-fi
-
-# Additional programs list screen
-if [[ "$1" == "-l" || "$1" == "--list" ]]; then
-    run_list
-    exit
-fi
-
-# Test for known flags
-for opt in $@
-do
-    case ${opt} in
-        -np|--no-packages) no_packages=true ;;
-        -ns|--no-sync) no_sync=true ;;
-        -*|--*) log_warning "Warning: invalid option ${opt}" ;;
-    esac
-done
+check_dotfiles() {
+    if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
+        printf "$(tput setaf 7)Downloading dotfiles...$(tput sgr0)\n"
+        mkdir ${DOTFILES_DIRECTORY}
+        curl -fsSL ${DOTFILES_TARBALL_PATH} | tar -xzC ${DOTFILES_DIRECTORY} --strip-components 1
+    fi
+}
 
 # Before relying on Homebrew, check that packages can be compiled
-if ! type_exists 'gcc'; then
-    log_error "The XCode Command Line Tools must be installed first"
-    printf "  Download them from: https://developer.apple.com/downloads\n"
-    printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
-    exit 1
-fi
+check_gcc() {
+    if ! type_exists 'gcc'; then
+        log_error "The XCode Command Line Tools must be installed first"
+        printf "  Download them from: https://developer.apple.com/downloads\n"
+        printf "  Then run: bash ~/.dotfiles/bin/dotfiles\n"
+        exit 1
+    fi
+}
 
 # Check for Homebrew
-if ! type_exists 'brew'; then
-    log_header "Installing Homebrew..."
-    ruby -e "$(curl -fsSkL https://raw.github.com/Homebrew/homebrew/go/install)"
-fi
+check_brew() {
+    if ! type_exists 'brew'; then
+        log_header "Installing Homebrew..."
+        ruby -e "$(curl -fsSkL https://raw.github.com/Homebrew/homebrew/go/install)"
+    fi
+}
 
 # Check for git
-if ! type_exists 'git'; then
-    log_header "Updating Homebrew..."
-    brew update
-    log_header "Installing Git..."
-    brew install git
-fi
+check_git() {
+    if ! type_exists 'git'; then
+        log_header "Updating Homebrew..."
+        brew update &> /dev/null
+        log_header "Installing Git..."
+        brew install git
+    fi
+}
+
+# Check for nvm
+check_nvm() {
+    if ! type_exists 'node'; then
+        log_header "Installing nvm..."
+        curl -fsSL https://raw.githubusercontent.com/creationix/nvm/v0.14.0/install.sh | bash
+    fi
+}
+
+# Check for node
+check_node() {
+    local version="0.10"
+
+    if ! type_exists 'node'; then
+        log_header "Installing node..."
+        nvm install ${version}
+        nvm alias default ${version}
+    fi
+}
 
 # Initialize the git repository if it's missing
-if ! is_git_repo; then
-    log_header "Initializing git repository..."
-    git init
-    git remote add origin ${DOTFILES_GIT_REMOTE}
-    git fetch origin master
-    # Reset the index and working tree to the fetched HEAD
-    # (submodules are cloned in the subsequent sync step)
-    git reset --hard FETCH_HEAD
-    # Remove any untracked files
-    git clean -fd
-fi
+run_init() {
+    if ! is_git_repo; then
+        log_header "Initializing git repository..."
+        git init &> /dev/null
+        git remote add origin ${DOTFILES_GIT_REMOTE} &> /dev/null
+    fi
+}
 
 # Conditionally sync with the remote repository
-if [[ ${no_sync} ]]; then
-    printf "Skipped dotfiles sync.\n"
-else
-    log_header "Syncing dotfiles..."
-    git pull --rebase origin master
-fi
+run_sync() {
+    if [[ ${no_sync} ]]; then
+        printf "Skipped dotfiles sync\n"
+    else
+        log_header "Syncing dotfiles..."
+        git fetch origin master
+        # Reset the index and working tree to the fetched HEAD
+        # (submodules are cloned in the subsequent sync step)
+        git reset --hard FETCH_HEAD
+        # Remove any untracked files
+        git clean -fd
+    fi
+}
 
 # Install and update packages
-if [[ ${no_packages} ]]; then
-    printf "Skipped package installations.\n"
-else
-    run_brew
-    run_npm
-    run_subl
-fi
+run_packages() {
+    if [[ ${no_packages} ]]; then
+        printf "Skipped package installations\n"
+    else
+        source ./lib/brew
+        run_brew
+        source ./lib/npm
+        run_npm
+    fi
+}
 
 # Force create/replace symlink
 link() {
     ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
 }
 
+# Copy and symlink files
 mirrorfiles() {
     # Copy `.gitconfig`.
     # Any global git commands in `~/.bash_profile.local` will be written to
@@ -109,35 +126,90 @@ mirrorfiles() {
     # Create the necessary symbolic links between the `.dotfiles` and `HOME`
     # directory. The `bash_profile` sources other files directly from the
     # `.dotfiles` repository.
-    link "atom/config.cson"   ".atom/config.cson"
-    link "atom/snippets.cson" ".atom/snippets.cson"
-    link "atom/styles.css"    ".atom/styles.css"
     link "bash/bashrc"        ".bashrc"
     link "bash/bash_profile"  ".bash_profile"
     link "bash/inputrc"       ".inputrc"
     link "git/gitattributes"  ".gitattributes"
     link "git/gitignore"      ".gitignore"
-
-    log_success "Dotfiles update complete!"
 }
 
 # Ask before potentially overwriting files
-seek_confirmation "Warning: This step may overwrite your existing dotfiles."
+confirm_dotfiles() {
+    seek_confirmation "Warning: This step may overwrite your existing dotfiles"
 
-if is_confirmed; then
-    mirrorfiles
-    source ${HOME}/.bash_profile
-else
-    printf "Aborting...\n"
-    exit 1
-fi
+    if is_confirmed; then
+        mirrorfiles
+        log_success "Dotfiles update complete!"
+        source ${HOME}/.bash_profile
+    else
+        printf "Aborting...\n"
+        exit 1
+    fi
+}
 
 # Ask before potentially overwriting OS X defaults
-seek_confirmation "Warning: This step may modify your OS X system defaults."
+confirm_osx() {
+    seek_confirmation "Warning: This step may modify your OS X system defaults"
 
-if is_confirmed; then
-    bash ./bin/osxdefaults
-    log_success "OS X settings updated! You may need to restart."
-else
-    printf "Skipped OS X settings update.\n"
-fi
+    if is_confirmed; then
+        bash ./bin/osxdefaults
+        log_success "OS X settings updated!"
+    else
+        printf "Skipped OS X settings update\n"
+    fi
+}
+
+# Ask before potentially overwriting ST3 preferences
+confirm_slt() {
+    seek_confirmation "Warning: This step may overwrite your existing ST3 preferences"
+
+    if is_confirmed; then
+        source ./lib/subl
+        run_subl
+        log_success "ST3 preferences updated!"
+    else
+        printf "Skipped ST3 preferences update\n"
+    fi
+}
+
+# Run
+run() {
+    # Check if dotfiles are installed
+    check_dotfiles
+
+    # cd into ~/.dotfiles
+    cd ${DOTFILES_DIRECTORY}
+
+    # Parse options
+    parse_opts "$@"
+
+    # Show help
+    if [[ ${help} ]]; then
+        run_help
+        exit
+    fi
+
+    # Source utils
+    source ./lib/utils
+
+    # Run checks
+    check_gcc
+    check_brew
+    check_git
+    check_nvm
+    check_node
+
+    # Init repo and sync files
+    run_init
+    run_sync
+
+    # Install packages
+    run_packages
+
+    # Confirm before applying settings
+    confirm_dotfiles
+    confirm_osx
+    confirm_slt
+}
+
+run "$@"
